### PR TITLE
update to support HA 0.96 and feature enhancements

### PR DESCRIPTION
**Pull request by raman325**
See #12. This change is fully backwards compatible with existing usage of this card aside from the fact that it now only supports 0.96.0 or greater because of breaking changes introduced to the thermostat component

- Update code to handle breaking changes as a result of the HA 0.96.0 release
- Add support for dual temperature single entity thermostat
- Add support to configure range sliderType to always be visible while thermostat is not off

### CODE REVIEW

**Comment by Chaotic** [comment]
I just installed your fork to test this (WAF needs a thermostat card) and it is working and showing my thermostat correctly however there isn't a button to put it in heat_cool mode.

I have a zwave themostat that has it split into a heat/cool entities and it supports a heat_cool mode (I can set it manually)

here is my yaml from lovelace.
`  - type: custom:dual-thermostat
    name: Thermostat
    entities:
      - entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
        type: cool
      - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
        type: heat
    fan_control: true
    min_slider: 50
    max_slider: 90
    always_use_range_slider: true`

Also since I'm posting anyways I think the always_use_range_slider should default to true since that is the way most people are used to.

thanks for the quick fix to get this card working with .96

**Comment by smartiq** [comment]
Since my homeassistant dual-thermostat card been busted since the 0.96 upgrade, I decided to test this as well.

It didn't work out of the box with my previous ui-lovelace.yaml file and gave me the following error:
```
t.entities is not iterable

{
  "type": "custom:dual-thermostat",
  "name": "Home Thermostat",
  "entities": {
    "cool": "climate.home_thermostat_cooling_1",
    "heat": "climate.home_thermostat_heating_1"
  },
  "fan_control": true,
  "min_slider": 60,
  "max_slider": 80
}
```

I changed the entities from a dictionary of cool/heat to an array instead:
```
                   - type: custom:dual-thermostat
                     name: Home Thermostat
                     entities:
-                         cool: climate.home_thermostat_cooling_1
-                         heat: climate.home_thermostat_heating_1
+                         - climate.home_thermostat_cooling_1
+                         - climate.home_thermostat_heating_1
                     fan_control: true
                     min_slider: 60
                     max_slider: 80

```

And then ran into the same issue as @Chaotic where I had heat/cool/off, but no heat_cool.

Not certain if this breakage is a bug, or if I had the syntax wrong before and it just worked.
Thanks again for getting this PR open so quick!

Barry

**Comment by smartiq** [comment]
Re-reading the README.md, I was off in the weeds before so feel free to ignore that "issue".  I should have had:

```
                  - type: custom:dual-thermostat
                    name: Home Thermostat
                    entities:
                         - type: cool
                           entity: climate.home_thermostat_cooling_1
                         - type: heat
                           entity: climate.home_thermostat_heating_1
                    fan_control: true
                    min_slider: 60
                    max_slider: 80
                    always_use_range_slider: true

```
The fact it didn't blow up before didn't mean it was correct :-/

Thanks,

Barry

**Comment by raman325** [comment]
@chaotic as far as I understand the change, it's on the component to distinguish between `heat_cool` and `auto` but you are right that the icon handling doesn't account for this. I will work on a fix soon (I'm learning JS as I go so it might take me a bit)

@smartiq I had to clear my cache after the changes - I saw a similar error but it was due to Chrome caching the original library before the changes

**Comment by raman325** [comment]
I'm not sure if this will fix it because I don't have the right component to test. Let me know what you find when you test the above @Chaotic

**Comment by Chaotic** [comment]
Tested the new change and it looks good.

And yes the component now reports heat_cool instead of auto but without an icon there was no way to put it in heat_cool since it wasn't in the icon list.

Thanks for the quick responses.

**Comment by enriqg9** [comment]
Yes, the heat_cool wasn't rendered because it was missing on the available options, there are also some css changes that need to be incorporated, I will incorporate when merging. 

A few thoughts I had while reviewing. The native component already supports thermostats with low/high points so I don't think there's a need to add support for a single entity to replicate this behavior, this is beyond the scope of this card.

Also, the always_use_range_slider option is a targeted fix with very specific use-case. Other than that, great job adding support to 0.96, I will tag it with a different version number as changes will break usage for older versions.

**Comment by raman325** [comment]
@enriqg9 

Regarding point 1: Makes sense, I actually tried to find the code for the native thermostat card to check if this was worth it but couldn't find it. Could you point me to the code?

Regarding point 2: You're right, the new configuration option is for a very specific use case. I didn't see the harm in adding it since it was built to be backwards compatible but your call whether to include it.

Regarding 0.96 support: I am happy to submit a separate pull request that's just focused on supporting 0.96 and not including the above two additional features, just let me know if that's what you'd like

**Comment by raman325** [comment]
And regarding my change to support `heat_cool`, the changes I made *should* work as long as the thermostat doesn't support both `auto` and `heat_cool` as separate options. Based on the explanation provided in the release notes, I don't think there is an expectation that a thermostat would support both, but it would be a quick change to support both if needed, we would just need to find a new icon to distinguish between the two

**Comment by enriqg9** [comment]
@raman325 the code for the native card is in the [Polymer repo](https://github.com/home-assistant/home-assistant-polymer/blob/20190719.0/src/panels/lovelace/cards/hui-thermostat-card.ts). Auto already has a different Icon check the latest commit and let me know if you find anything needing to be fixed.

**Comment by raman325** [comment]
Doh I was looking in the `src/cards` path. Thanks!

**Pull request closed without merging**
