### PR TITLE
I made some changes to allow the slider's min and max to be configured via the lovelace yaml

### PR DESCRIPTION
**Pull request by simpat1zq**
I had asked about this as an option on [THIS POST](https://community.home-assistant.io/t/dual-thermostat-card/85798/19?u=simpat1zq). I was told that it was set by the thermostat attributes in HA. So I updated the code to allow for 2 more option in the LoveLace config: min_slider and max slider. 

They allow you to set the min and the max on the slider, regardless of what it is set on the attributes in HA for that thermostat. I have tested this myself, and have confirmed that this is a non-breaking change, so there is no requirement to update any configs. 

I have also updated the readme to reflect these 2 new options. I'm not exactly sure what the app.js is doing, so I believe there is a chance that the changes I made in there aren't all necessary. Could you please take a look at that and make sure there wasn't anything I put in there that didn't need to be changed.

### CODE REVIEW

**Comment by enriqg9** [comment]
Thanks, I'll review and let you know, app.js is the source code dual-thermostat.js is the compiled output of webpack.

**Comment by simpat1zq** [comment]
Oh OK. In that case, if something needs to be compiled, then I might have missed something. I edited apps.js first, but that didn't seem to do a whole lot, so I edited dual-thermostat.js, and I got what I wanted. I guess I didn't really test the apps.js changes then.

**Comment by simpat1zq** [comment]
I made the change. Let me know if you need me to do anything else.

**Comment by enriqg9** [comment]
@simpat1zq all merged and compiled, try to replace your dual-thermostat.js and let me know if it works as expected.

**Pull request merged**
